---

version: '3'
services:

  skccentos:
    build: skc-ruby
    image: skc-ruby-base
    
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
